// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwyBHyL31CmVWvJiKVERMOjwFlCfwtrM',
    appId: '1:862841925597:web:75d1962cd19aeadaf7d034',
    messagingSenderId: '862841925597',
    projectId: 'zulu-cec73',
    authDomain: 'zulu-cec73.firebaseapp.com',
    storageBucket: 'zulu-cec73.appspot.com',
    measurementId: 'G-SHWGMKVC54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfErE7dNmso_DVpwXfOEge6ZUqEJqSaw',
    appId: '1:862841925597:android:a47110064bf9dfc8f7d034',
    messagingSenderId: '862841925597',
    projectId: 'zulu-cec73',
    storageBucket: 'zulu-cec73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKVtL5v1HtAbrfFtJWhLXqMyzEPBAqmk',
    appId: '1:862841925597:ios:1651a20fd1194a8df7d034',
    messagingSenderId: '862841925597',
    projectId: 'zulu-cec73',
    storageBucket: 'zulu-cec73.appspot.com',
    iosBundleId: 'com.example.zulufire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKVtL5v1HtAbrfFtJWhLXqMyzEPBAqmk',
    appId: '1:862841925597:ios:23cc3a202d6e7d68f7d034',
    messagingSenderId: '862841925597',
    projectId: 'zulu-cec73',
    storageBucket: 'zulu-cec73.appspot.com',
    iosBundleId: 'com.example.zulufire.RunnerTests',
  );
}
